routes/web.php
<?php

Route::get('/', 'WelcomeController@index')->name('index');
Route::get('/aboutUs', 'WelcomeController@abouts')->name('about');
Route::get('/services/{id?}', 'WelcomeController@service')->name('service');

Route::get('/blog/news', 'WelcomeController@blogitems')->name('blognews');
Route::get('/blog/{id}', 'WelcomeController@blogid')->name('blogid');
Route::get('/contact', 'WelcomeController@contact')->name('contact');
Route::post('/send', 'WelcomeController@send')->name('send');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/contact', 'ContactController');

    
    Route::resource('users', 'UsersController');
    Route::resource('slider', 'SliderController');
    Route::resource('about', 'AboutParentController');
    Route::resource('aboutinform', 'AboutInformController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');
    Route::resource('blog', 'BlogController');
    Route::resource('service', 'ServiceController');
    Route::resource('service', 'ServiceController');
    Route::resource('service_info', 'ServiceInformateController');
    Route::resource('bcomments', 'BlogCommentsController');
    Route::post('bcomments/delete', 'BlogCommentsController@delete')->name('comment.delete');
});

resources/views/admin/about/informate/create.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">
        <div class="card-header">
            {{ trans('global.create') }}
        </div>

        <div class="card-body">
            <form action="{{ route("admin.aboutinform.store") }}" method="POST" enctype="multipart/form-data">
                @csrf



                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label for="title">Заглавие</label>
                    <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($aboutinform) ? $aboutinform->name : '') }}" required>
                    @if($errors->has('title'))
                        <em class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </em>
                    @endif
                </div>


                <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                    <label for="description">Описание </label>
                    <textarea id="description" name="description" class="form-control" required>{{ old('description', isset($aboutinform) ? $aboutinform->description : '') }}</textarea>
                    @if($errors->has('description'))
                        <em class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </em>
                    @endif
                </div>

                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/about/informate/edit.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">
        <div class="card-header">
            Редактировать:
        </div>

        <div class="card-body">
            <form action="{{ route("admin.aboutinform.update",$id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('put')

                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label for="title">Заглавие</label>
                    <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($aboutinform) ? $aboutinform->title : '') }}" required>
                    @if($errors->has('title'))
                        <em class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </em>
                    @endif
                </div>


                <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                    <label for="description">Описание </label>
                    <textarea id="description" name="description" class="form-control" required>{{ old('description', isset($aboutinform) ? $aboutinform->description : '') }}</textarea>
                    @if($errors->has('description'))
                        <em class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </em>
                    @endif
                </div>
                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/about/informate/index.blade.php
@extends('admin.layouts.admin')
@section('content')


    <!-- Breadcrumb Area -->

    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">О нас </li>
            </ol>
        </nav>
    </div>
    @can('about_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.aboutinform.create") }}">
                Опубликовано
            </a>
        </div>
    </div>
    @endcan
    <!-- Wrapper -->
    <div class="wrapper wrapper-content blog">
        <div class="container-fluid">
            <div class="row">

                @foreach($aboutinform as $key => $inform)
                    <div class="col-md-6 col-lg-4">
                        <!-- Ibox -->
                        <div class="ibox bg-boxshadow mb-50">
                            <!-- Content -->
                            <div class="ibox-content blog">
                                <a href="">
                                    <h4>{{ $inform->title ?? '' }}</h4>
                                </a>
                                <p>  {{ $inform->description ?? '' }}   </p>

                                <div class="row">
                                    <div class="col-md-8">
                                        <h5 class="blog-tag">Настройка:</h5>

                                        @can('about_edit')
                                        <button class="btn btn-white btn-xs blog" type="button" onclick="location.href='{{route('admin.aboutinform.edit',$inform->id)}}'">Редактировать</button>
                                        @endcan

                                        @can('about_delete')
                                            <form action="{{ route('admin.aboutinform.destroy', $inform->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <button class="btn  btn-danger btn-xs blog" type="submit">Удалить</button>
                                            </form>
                                        @endcan
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                @endforeach

            </div>
        </div>
    </div>



@endsection