routes/web.php
<?php

Route::get('/', 'WelcomeController@index')->name('index');
Route::get('/aboutUs', 'WelcomeController@abouts')->name('about');
Route::get('/services/{id?}', 'WelcomeController@service')->name('service');

Route::get('/blog/news', 'WelcomeController@blogitems')->name('blognews');
Route::get('/blog/{id}', 'WelcomeController@blogid')->name('blogid');
Route::get('/contact', 'WelcomeController@contact')->name('contact');
Route::post('/send', 'WelcomeController@send')->name('send');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/contact', 'ContactController');

    
    Route::resource('users', 'UsersController');
    Route::resource('slider', 'SliderController');
    Route::resource('about', 'AboutParentController');
    Route::resource('aboutinform', 'AboutInformController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');
    Route::resource('blog', 'BlogController');
    Route::resource('service', 'ServiceController');
    Route::resource('service', 'ServiceController');
    Route::resource('service_info', 'ServiceInformateController');
    Route::resource('bcomments', 'BlogCommentsController');
    Route::post('bcomments/delete', 'BlogCommentsController@delete')->name('comment.delete');
});

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\BlogCommentsModels;
use App\Models\BlogModels;
use Illuminate\Http\Request;
use App\Http\Controllers\Admin\AdminControoler;
use Intervention\Image\Facades\Image;

class BlogController extends AdminControoler
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blog=BlogModels::get();

        return view('admin.blog.index', compact('blog'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if ($request->has('avatar')) {

            $imagename = date("Y") . '/' . date("m") . '/' . rand(1, 99999) . '.' . $request->avatar->getClientOriginalExtension();

            $destinationPath = public_path('blog/');
            $pah = public_path('blog/' . date("Y") . '/' . date("m"));
            if (!file_exists($pah) > 0):
                if (!is_dir($pah . date("Y") . '/' . date("m"))) {
                    mkdir($pah, 0755, true);
                }endif;

            $thumb_img = Image::make($request->avatar->getRealPath())->encode('jpg', 75);
            $thumb_img->save($destinationPath . '/' . $imagename, 80);

            BlogModels::create([
                'name'=>$request['name'],
                'info'=>$request['info'],
                'auth_offer'=>$request['auth_offer'],
                'auth'=>auth()->user()->id,
                'url'=>$request['url'],
                'avatar'=>'blog/'.$imagename,
            ]);

            return redirect()->route('admin.blog.index');
        }else{

            return back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog=BlogModels::find($id);
        $blogComments=BlogCommentsModels::where('blog_id',$id)->orderby('id','desc')->paginate(8);
        return view('admin.blog.show',compact('blog','blogComments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog=BlogModels::find($id);
        return view('admin.blog.edit',compact('blog','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->has('avatar')) {

            $imagename = date("Y") . '/' . date("m") . '/' . rand(1, 99999) . '.' . $request->avatar->getClientOriginalExtension();

            $destinationPath = public_path('blog/');
            $pah = public_path('blog/' . date("Y") . '/' . date("m"));
            if (!file_exists($pah) > 0):
                if (!is_dir($pah . date("Y") . '/' . date("m"))) {
                    mkdir($pah, 0755, true);
                }endif;

            $thumb_img = Image::make($request->avatar->getRealPath())->encode('jpg', 75);
            $thumb_img->save($destinationPath . '/' . $imagename, 80);

            BlogModels::find($id)->update([
                'name'=>$request['name'],
                'info'=>$request['info'],
                'auth_offer'=>$request['auth_offer'],
                'auth'=>auth()->user()->id,
                'url'=>$request['url'],
                'avatar'=>'blog/'.$imagename,
            ]);

            return back();
        }else{
            BlogModels::find($id)->update([
                'auth_offer'=>$request['auth_offer'],
                'auth'=>auth()->user()->id,
                'name'=>$request['name'],
                'info'=>$request['info'],
                'url'=>$request['url'],

            ]);
            return back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        BlogModels::find($id)->delete();
        return back();
    }
}

resources/views/admin/blog/create.blade.php
@extends('admin.layouts.admin')

@section('content')

    <div class="card">


        <div class="card-body">
            <form action="{{ route("admin.blog.store") }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group {{ $errors->has('url') ? 'has-error' : '' }}">
                    <label for="description">Youtube Link</label>
                    <br>
                    <input type="url" name="url" value="" class="form-control">
                    @if($errors->has('url'))
                        <em class="invalid-feedback">
                            {{ $errors->first('url') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('auth_offer') ? 'has-error' : '' }}" >
                    <label for="description">предложение авторизации пользователя</label>
                    <br>
                    <textarea name="auth_offer" class="form-control" required></textarea>
                    @if($errors->has('auth_offer'))
                        <em class="invalid-feedback">
                            {{ $errors->first('auth_offer') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    <label for="name">Заглавие</label>
                    <input type="text" id="name" name="name" class="form-control" value="" required>
                    @if($errors->has('name'))
                        <em class="invalid-feedback">
                            {{ $errors->first('name') }}
                        </em>
                    @endif
                </div>


                <div class="form-group {{ $errors->has('info_ru') ? 'has-error' : '' }}">
                    <label for="description">Описание </label>
                    <textarea id="description" name="info" class="form-control inputFields ncontent" required></textarea>
                    @if($errors->has('info'))
                        <em class="invalid-feedback">
                            {{ $errors->first('info') }}
                        </em>
                    @endif
                </div>

                <div class="form-group {{ $errors->has('avatar') ? 'has-error' : '' }}">
                    <label for="name">Фото*</label>
                    <input type="file" id="name" name="avatar" class="form-control" required>
                    @if($errors->has('avatar'))
                        <em class="invalid-feedback">
                            {{ $errors->first('avatar') }}
                        </em>
                    @endif
                </div>
                <div>
                    <input class="btn btn-danger" type="submit" value="Подтвердите">
                </div>
            </form>
        </div>
    </div>

@endsection
@section('js')

    <script>
        $(function () {
            $("#date").datetime({value: '+1min'});
            $("#update_cmd").button();
            $("#status").buttonset();
            $("#top_fut").buttonset();
            $("#lang").buttonset();
            $("#catList").buttonset();
        });
        tinymce.init({
            selector: '.ncontent',
            menubar: false,
            plugins: [
                "advlist autolink link image lists charmap print preview hr anchor pagebreak fullscreen",
                "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking spellchecker",
                "table contextmenu directionality emoticons paste textcolor responsivefilemanager code"
            ],
            relative_urls: false,
            image_advtab: true,
            filemanager_title: "Responsive Filemanager",
            file_picker_types: 'file image media',
            external_filemanager_path: "/admin/filemanager/",
            toolbar1: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent blockquote | formatselect removeformat | fullscreen",
            toolbar2: "undo redo | cut copy paste pastetext | forecolor backcolor | searchreplace  | responsivefilemanager | image | media | link unlink  | code",
            file_picker_callback: function (cb, value, meta) {
                var width = window.innerWidth - 30;
                var height = window.innerHeight - 60;
                if (width > 1800) width = 1800;
                if (height > 1200) height = 1200;
                if (width > 600) {
                    var width_reduce = (width - 20) % 138;
                    width = width - width_reduce + 10;
                }
                var urltype = 2;
                if (meta.filetype == 'image') {
                    urltype = 1;
                }
                if (meta.filetype == 'media') {
                    urltype = 3;
                }
                let title = "RESPONSIVE FileManager";
                if (typeof this.settings.filemanager_title !== "undefined" && this.settings.filemanager_title) {
                    title = this.settings.filemanager_title;
                }
                let akey = "key";
                if (typeof this.settings.filemanager_access_key !== "undefined" && this.settings.filemanager_access_key) {
                    akey = this.settings.filemanager_access_key;
                }
                let sort_by = "";
                if (typeof this.settings.filemanager_sort_by !== "undefined" && this.settings.filemanager_sort_by) {
                    sort_by = "&sort_by=" + this.settings.filemanager_sort_by;
                }
                let descending = "false";
                if (typeof this.settings.filemanager_descending !== "undefined" && this.settings.filemanager_descending) {
                    descending = this.settings.filemanager_descending;
                }
                let fldr = "";
                if (typeof this.settings.filemanager_subfolder !== "undefined" && this.settings.filemanager_subfolder) {
                    fldr = "&fldr=" + this.settings.filemanager_subfolder;
                }
                let crossdomain = "";
                if (typeof this.settings.filemanager_crossdomain !== "undefined" && this.settings.filemanager_crossdomain) {
                    crossdomain = "&crossdomain=1";

                    // Add handler for a message from ResponsiveFilemanager
                    if (window.addEventListener) {
                        window.addEventListener('message', filemanager_onMessage, false);
                    } else {
                        window.attachEvent('onmessage', filemanager_onMessage);
                    }
                }
                tinymce.activeEditor.windowManager.open({
                    title: title,
                    file: this.settings.external_filemanager_path + 'dialog.php?type=' + urltype + '&descending=' + descending + sort_by + fldr + crossdomain + '&lang=' + this.settings.language + '&akey=' + akey,
                    width: width,
                    height: height,
                    resizable: true,
                    maximizable: true,
                    inline: 1
                }, {
                    setUrl: function (url) {
                        cb(url);
                    }
                });
            },
        });
    </script>


@endsection

resources/views/admin/blog/index.blade.php
@extends('admin.layouts.admin')
@section('content')


    <!-- Breadcrumb Area -->

    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Блог</li>
            </ol>
        </nav>
    </div>

    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            @can('news_create')
            <a class="btn btn-success" href="{{ route("admin.blog.create") }}">
                Опубликовано
            </a>
            @endcan
        </div>
    </div>
    <!-- Wrapper -->
    <div class="wrapper wrapper-content blog">
        <div class="container-fluid">
            <div class="row">

                @foreach($blog as $key => $bloger)
                <div class="col-md-6 col-lg-4">
                    <!-- Ibox -->
                    <div class="ibox bg-boxshadow mb-50">
                        <!-- Content -->
                        <div class="ibox-content blog">
                            <a >
                                <h4>{{ $bloger->name ?? '' }}</h4>
                            </a>
                            <!-- Date -->
                            <div class="blog-date">
                                <p><strong>{{$bloger->user->name}}</strong> <span><i class="fa fa-clock-o"></i> {{$bloger->created_at->format(' M d Y H:i')}}</span>
                                </p>
                            </div>
                            <p>    {{ mb_strlen( strip_tags($bloger->info, '<b><i><u>') ) > 300 ? mb_substr(strip_tags($bloger->info, '<b><i><u>'), 0, 300) . ' ...' : strip_tags($bloger->info, '<b><i><u>') }}
                            </p>

                            <div class="row">
                                <div class="col-md-8">
                                    <h5 class="blog-tag">Настройка:</h5>
                                    @can('news_edit')
                                    <button class="btn btn-white btn-xs blog" type="button" onclick="location.href='{{route('admin.blog.edit',$bloger->id)}}'">Редактировать</button>
                                    @endcan
                                    @can('news_delete')
                                        <form action="{{ route('admin.blog.destroy', $bloger->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button class="btn  btn-danger btn-xs blog" type="submit">Удалить</button>
                                        </form>
                                    @endcan
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                      @endforeach

            </div>
        </div>
    </div>


@endsection

resources/views/admin/blog/show.blade.php
@extends('admin.layouts.admin')
@section('content')

    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Գլխավո</a></li>
                <li class="breadcrumb-item"><a href="{{route('admin.blog.index')}}">Բլոգ</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{$blog->name_am}}</li>
            </ol>
        </nav>
    </div>

<!-- Wrapper -->
<div class="wrapper wrapper-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="product--item-arae bg-boxshadow">
                    <!-- Media -->
                    <div class="media align-items-center py-3 mb-4">
                        <img src="{{asset($blog->avatar)}}" alt="" class="product-thumb d-block">
                        <!-- Media Body -->
                        <div class="media-body ml-4">
                            <h4 class="mb-15">{{$blog->name_am}}</h4>
                            <a href="{{route('admin.blog.edit',$blog->id)}}" class="btn btn-primary btn-sm mb-15">Փոփոխել</a>&nbsp;
                            <a href="{{route('admin.blog.index')}}" class="btn btn-default btn-sm mb-15">Անցնել գլխավոր բլոգներ</a>
                        </div>
                    </div>

                    <!-- Nav Tabs -->
                    <div class="nav-tabs-top">
                        <ul class="nav nav-tabs">
                            <!-- Nav Item -->
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#item-overview">Հայերեն</a>
                            </li>
                            <!-- Nav Item -->
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#item-description">Ռուսերեն</a>
                            </li>
                            <!-- Nav Item -->
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#item-discounts">Անգլերեն</a>
                            </li>
                            <!-- Nav Item -->
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#item-images">Հավելյար ինֆորմացյա</a>
                            </li>  <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#item-Comments">Comments</a>
                            </li>
                        </ul>

                        <!-- Tab Content -->
                        <div class="tab-content">
                            <!-- Overview -->
                            <div class="tab-pane fade show active" id="item-overview">

                                <div class="card-body product-item-table">
                                    <h6 class="large font-weight-semibold mb-4">Ինֆօրմացյա</h6>
                                    <!-- Table -->
                                    <table class="table">
                                        <tbody>
                                        <tr>
                                            <td>Վերնագիր:</td>
                                            <td>{{$blog->name_am}}</td>
                                        </tr>
                                        <tr>
                                            <td>Նկարագրություն:</td>
                                            <td>   {!! $blog->info_am !!}</td>
                                        </tr>


                                        </tbody>
                                    </table>

                                </div>

                            </div>


                            <!-- Item Description -->
                            <div class="tab-pane fade" id="item-description">
                                <div class="card-body p-3">

                                    <div class="row">

                                        <h6 class="large font-weight-semibold mb-4">Ինֆօրմացյա</h6>
                                        <!-- Table -->
                                        <table class="table">
                                            <tbody>
                                            <tr>
                                                <td>Վերնագիր:</td>
                                                <td>{{$blog->name_ru}}</td>
                                            </tr>
                                            <tr>
                                                <td>Նկարագրություն:</td>
                                                <td>   {!! $blog->info_ru !!}</td>
                                            </tr>


                                            </tbody>
                                        </table>

                                    </div>

                                </div>
                            </div>

                            <!-- Item Discounts -->
                            <div class="tab-pane fade" id="item-discounts">
                                <div class="card-body">
                                    <!-- Table Responsive -->
                                    <div class="table-responsive">
                                        <h6 class="large font-weight-semibold mb-4">Ինֆօրմացյա</h6>
                                        <!-- Table -->
                                        <table class="table">
                                            <tbody>
                                            <tr>
                                                <td>Վերնագիր:</td>
                                                <td>{{$blog->name_en}}</td>
                                            </tr>
                                            <tr>
                                                <td>Նկարագրություն:</td>
                                                <td>   {!! $blog->info_en !!}</td>
                                            </tr>


                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>
                            <!-- / Discounts -->

                            <!-- Images -->
                            <div class="tab-pane fade" id="item-images">
                                <div class="card-body">

                                    <div class="mb-4">
                                        <span class="badge badge-dot badge-primary"></span> Primary image
                                    </div>

                                    <!-- Lightbox template -->

                                    <!-- Item Image -->
                                    <div id="product-item-images" class="row">
                                        <div class="col-12 col-sm-6 col-md-4 col-xl-3 mb-4">
                                            <a href="{{asset($blog->avatar)}}" class="d-block"><img src="{{asset($blog->avatar)}}" class="img-fluid" alt=""></a>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-8 col-xl-9 mb-8">
                                            <iframe width="1200" src="{{$blog->url}}" frameborder="0" allowfullscreen  >

                                            </iframe>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="item-Comments">
                                <div class="card-body">

                                    <div class="mb-4">
                                        <span class="badge badge-dot badge-primary"></span> Primary Comments
                                    </div>

                                    <!-- Lightbox template -->

                                    <!-- Item Image -->
                                    <div id="product-item-images" class="row">
                                        <div class="row">
                                            <!-- Comments -->
                                            <div class="col-lg-12">
                                                <div class="articles-heading mt-30">
                                                    <h2>Comments:</h2>
                                                    {{$blogComments->links()}}
                                                </div>

<div class="oks col-lg-12">


            @foreach($blogComments->reverse() as $comments)
            <div class="article-social-feed-box id-{{$comments->id}}">
                <!-- Social Avatar -->
                <div class="social-avatar">
                    <a href="#" class="social-image"><img src="img/thumbnails-img/blog-1.jpg" alt=""></a>
                    <!-- Media Body -->
                    <div class="media-body">
                        <a href="#">Andrew Williams,</a>
                        <small>Today 4:21 pm - 12.06.2018</small>



                        <input type="hidden" name="id" id="comments_id" value="{{$comments->id}}">
                        <button class="btn  btn-danger btn-xs blog" type="button" onclick="deletecommens()">Ջնջել</button>

                    </div>
                </div>
                <!-- Social Body -->
                <div class="social-body">
                    <p>{{$comments->message}}</p>
                </div>
            </div>

@endforeach
</div>



                                                <form action="javascript::void(0)" method="POST" id="ffre">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                </form>
                                                <div class="form-group {{ $errors->has('message') ? 'has-error' : '' }}">
                                                    <label for="description">Նկարագրութհուն</label>
                                                    <textarea id="description" name="message" class="form-control" style="border: 1px solid black;">{{ old('message') }}</textarea>
                                                    <input type="hidden" name="blog_id" id="blog_id" value="{{$blog->id}}">

                                                </div>
                                                <div>
                                                    <input class="btn btn-danger jutak" type="button" value="Հաստատել" onclick="getUserAccount()">
                                                </div>

                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <!-- / Images -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <script>
        function getUserAccount() {
            var msg=document.getElementById('description').value;
            var blog=document.getElementById('blog_id').value;
    axios.post('{{route('admin.bcomments.store')}}',{'msg': msg,'blog':blog})
        .then(function (response) {

            $('.oks').append(response.data)
        })
}
function deletecommens() {

            var id=document.getElementById('comments_id').value;

    axios.post('{{route('admin.comment.delete')}}',{'id': id})
        .then(function (response) {
console.log(response.data);
            $('.id-'+response.data).remove().hide();
        })
}

    </script>
@endsection